<?php

namespace AppBundle\Repository;

/**
 * AddressHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
