<?php

namespace AppBundle\Repository;

/**
 * DisengegementReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisengegementReasonRepository extends \Doctrine\ORM\EntityRepository
{
}
