<?php

namespace AppBundle\Repository;

/**
 * IndividualIndividualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndividualIndividualRepository extends \Doctrine\ORM\EntityRepository
{
}
