<?php

namespace AppBundle\Repository;

/**
 * MaritialStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaritialStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
