<?php

namespace AppBundle\Repository;

/**
 * PersonTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
